version: '3.7'
services:
  db:
    container_name: db-dev
    image: mongo:4.4.2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: arc-dev
    ports:
      - 27017:27017

  db-viewer:
    container_name: db-viewer-dev
    image: mongo-express
    depends_on: 
      - db
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_SERVER: db-dev