const LOAD_EVENTS = {
  LOAD_STATUS_CHANGED: Symbol('LOAD_EVENTS.LOAD_STATUS_CHANGED')
};

const LOAD_STATUS = {
  IDLE: Symbol('LOAD_STATUS.IDLE'),
  LOADING: Symbol('LOAD_STATUS.LOADING')
};

export { LOAD_STATUS, LOAD_EVENTS };
