const AUTH_EVENTS = {
  AUTH_STATUS_CHANGED: Symbol('AUTH_EVENTS.AUTH_STATUS_CHANGED')
};

const AUTH_STATUSES = {
  UNSOLVED: Symbol('AUTH_STATUSES.UNSOLVED'),
  LOGGEDIN: Symbol('AUTH_STATUSES.LOGGEDIN'),
  LOGGEDOUT: Symbol('AUTH_STATUSES.LOGGEDOUT')
};

export { AUTH_EVENTS, AUTH_STATUSES };
