const LOAD_STATES = {
  IDLE: Symbol('LOAD_STATES.IDLE'),
  LOADING: Symbol('LOAD_STATES.LOADING')
};

const LOAD_EVENTS = {
  LOADING_STARTED: Symbol('LOAD_EVENTS.LOADING_STARTED'),
  LOADING_STOPPED: Symbol('LOAD_EVENTS.LOADING_STOPPED')
};

export { LOAD_STATES, LOAD_EVENTS };
