const AUTH_STATUSES = {
  UNSOLVED: 'AUTH_STATUSES.UNSOLVED',
  SIGNEDOUT: 'AUTH_STATUSES.SIGNEDOUT',
  PENDING: 'AUTH_STATUSES.PENDING',
  SIGNEDIN: 'AUTH_STATUSES.SIGNEDIN'
};

const AUTH_EVENTS = {
  USER_SIGNEDOUT: 'AUTH_EVENTS.USER_SIGNEDOUT',
  USER_SIGNEDIN: 'AUTH_EVENTS.USER_SIGNEDIN',
  AUTH_STATE_CHANGED: 'AUTH_EVENTS.AUTH_STATE_CHANGED',
  USER_CREATED: 'AUTH_EVENTS.USER_CREATED',
  USER_UPDATED: 'AUTH_EVENTS.USER_UPDATED'
};

export { AUTH_STATUSES, AUTH_EVENTS };
