const AUTH_STATUS = {
  UNSOLVED: Symbol('AUTH_STATUS.UNSOLVED'),
  LOGGEDIN: Symbol('AUTH_STATUS.LOGGEDIN'),
  LOGGEDOUT: Symbol('AUTH_STATUS.LOGGEDOUT')
};

const AUTH_EVENTS = {
  STATUS_CHANGED: Symbol('AUTH_EVENTS.STATUS_CHANGED'),
  SERVICE_STATE_CHANGED: Symbol('AUTH_EVENTS.SERVICE_STATE_CHANGED')
};

export { AUTH_STATUS, AUTH_EVENTS };
