const AUTH_STATUS = {
  UNSOLVED: Symbol('AUTH_STATUSES.UNSOLVED'),
  LOGGEDIN: Symbol('AUTH_STATUSES.LOGGEDIN'),
  LOGGEDOUT: Symbol('AUTH_STATUSES.LOGGEDOUT')
};

const AUTH_EVENTS = {
  STATUS_CHANGED: Symbol('AUTH_EVENTS.STATUS_CHANGED'),
  SERVICE_STATE_CHANGED: Symbol('AUTH_EVENTS.SERVICE_STATE_CHANGED')
};

export { AUTH_STATUS, AUTH_EVENTS };
