const AUTH_STATUS = {
  UNSOLVED: Symbol('AUTH_STATUS.UNSOLVED'),
  LOGGEDIN: Symbol('AUTH_STATUS.LOGGEDIN'),
  LOGGEDOUT: Symbol('AUTH_STATUS.LOGGEDOUT')
};

const AUTH_EVENTS = {
  AUTH_STATUS_CHANGED: Symbol('AUTH_EVENTS.AUTH_STATUS_CHANGED')
};

export { AUTH_STATUS, AUTH_EVENTS };
